### ISSUE TITLE
Error on PKHeX.Web: Value 66 not supported Arg_ParamName_Name, value

### ISSUE THREAD

**Issue by TitanicMT** [arleypadua/PKHeX.Everywhere#100]
# Error on PKHeX.Web

* **Id**: 12e68507-1ba5-4df8-a1b6-82abd6e1bd37
* **Game version**: SoulSilver
* **Generation**: Gen4
## Type
```
ArgumentOutOfRangeException
```

## Message
```
Value 66 not supported Arg_ParamName_Name, value
```

## Stack trace
```
   at PKHeX.Facade.Gender.FromByte(Byte value)
   at PKHeX.Facade.Trainer.get_Gender()
   at PKHeX.Web.Pages.Home.<BuildRenderTree>b__0_5(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at AntDesign.Descriptions.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

**Comment by arleypadua** [comment]
should be fixed on the next release in a few minutes ✅
