### ISSUE TITLE
Error on PKHeX.Web: Arg_KeyNotFoundWithKey, 255

### ISSUE THREAD

**Issue by Mathsys01** [arleypadua/PKHeX.Everywhere#105]
# Error on PKHeX.Web

* **Id**: 6295858f-7b71-4834-bc93-9b190e1ea948
* **Game version**: Crystal
* **Generation**: Gen2
## Type
```
KeyNotFoundException
```

## Message
```
Arg_KeyNotFoundWithKey, 255
```

## Stack trace
```
   at System.Collections.Generic.Dictionary`2[[System.UInt16, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[PKHeX.Facade.Repositories.ItemDefinition, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(UInt16 )
   at PKHeX.Facade.Repositories.ItemRepository.GetGameItem(UInt16 id)
   at PKHeX.Facade.Inventory.Item.get_Definition()
   at PKHeX.Web.Pages.Items.<>c.<BuildRenderTree>b__0_7(Item i)
   at System.Linq.Enumerable.IEnumerableWhereIterator`1[[PKHeX.Facade.Inventory.Item, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Collections.Generic.List`1[[PKHeX.Facade.Inventory.Item, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[Item](IEnumerable`1 )
   at PKHeX.Web.Pages.Items.<>c__DisplayClass0_0.<BuildRenderTree>b__6(RenderTreeBuilder __builder4)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

**Comment by arleypadua** [comment]
Would you be able to share with me your save file? I've seen these issues before but can't reproduce it, so a save file would be if great help

If you want to share you can do so by https://filebin.net/

**Comment by Mathsys01** [comment]
Hi, I put the file in the link you sentEm 1 de dez. de 2024 04:21, Arley Pádua ***@***.***> escreveu:
Would you be able to share with me your save file? I've seen these issues before but can't reproduce it, so a save file would be if great help
If you want to share you can do so by https://filebin.net/

**Comment by arleypadua** [comment]
Sorry, forgot to mention that when you upload, you would get a sharing link, like: `https://filebin.net/some_random_id`

**Comment by Mathsys01** [comment]
Oh, ok. My Bad. Try this linkhttps://filebin.net/5xah2bobm0i6o1isThanks Em 3 de dez. de 2024 16:31, Arley Pádua ***@***.***> escreveu:
Sorry, forgot to mention that when you upload, you would get a sharing link, like: https://filebin.net/some_random_id

**Comment by arleypadua** [comment]
Thanks for the file, another question to help me debugging: 


Is this a ROM hack or the normal Pokemon Crystal?

**Comment by Mathsys01** [comment]
Its normal CrystalEm 4 de dez. de 2024 05:09, Arley Pádua ***@***.***> escreveu:
Thanks for the file, another question to help me debugging:
Is this a ROM hack or the normal Pokemon Crystal?

**Comment by arleypadua** [comment]
All right, thanks for the save file, found a hidden item called "Collapsible bike" in the key items of your backpack 🤷🏽 

And for some reason this was not mapped in the database.. a fix should be out in a few minutes

**Comment by Mathsys01** [comment]
Você é brasileiro? Muito obrigado pela ajuda com o arquivo. Como faço pra baixar o arquivo corrigido?Em 5 de dez. de 2024 17:22, Arley Pádua ***@***.***> escreveu:
All right, thanks for the save file, found a hidden item called "Collapsible bike" in the key items of your backpack 🤷🏽
And for some reason this was not mapped in the database.. a fix should be out in a few minutes

**Comment by arleypadua** [comment]
Sou sim, mas como é um repositório que pode ter contribuição de outros países tendo a escrever em Ingles mesmo.

Eu subi uma correção na aplicação, e não no save.

Com a correção você pode editar o seu save sem problemas.
