### ISSUE TITLE
Error on PKHeX.Web: Arg_KeyNotFoundWithKey, 427

### ISSUE THREAD

**Issue by youneszolj** [arleypadua/PKHeX.Everywhere#106]
# Error on PKHeX.Web

* **Id**: 8be18118-e738-4f9c-ac3e-712ff692b6c0
* **Game version**: FireRed
* **Generation**: Gen3
## Type
```
KeyNotFoundException
```

## Message
```
Arg_KeyNotFoundWithKey, 427
```

## Stack trace
```
   at System.Collections.Generic.Dictionary`2[[System.UInt16, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[PKHeX.Facade.Repositories.ItemDefinition, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(UInt16 )
   at PKHeX.Facade.Repositories.ItemRepository.GetGameItem(UInt16 id)
   at PKHeX.Facade.Inventory.Item.get_Definition()
   at PKHeX.Web.Pages.Items.<>c.<BuildRenderTree>b__0_7(Item i)
   at System.Linq.Enumerable.IEnumerableWhereIterator`1[[PKHeX.Facade.Inventory.Item, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Collections.Generic.List`1[[PKHeX.Facade.Inventory.Item, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[Item](IEnumerable`1 )
   at PKHeX.Web.Pages.Items.<>c__DisplayClass0_0.<BuildRenderTree>b__6(RenderTreeBuilder __builder4)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

**Comment by arleypadua** [comment]
Same issue as [this one](https://github.com/arleypadua/PKHeX.Everywhere/issues/105#issuecomment-2509611076)

I unfortunately can't reproduce this issue, if you are willing to share you save file through https://filebin.net I'd gladly have a look at it.

**Comment by arleypadua** [comment]
Just pushed a version that should be out in a bit fixing it
