### ISSUE TITLE
Error on PKHeX.Web: Arg_ArgumentOutOfRangeException Arg_ParamName_Name, index

### ISSUE THREAD

**Issue by ca122** [arleypadua/PKHeX.Everywhere#55]
# Error on PKHeX.Web

* **Id**: 143bb412-83f0-4dba-bd55-4457e879933f
* **Game version**: Let's Go, Eevee!
* **Generation**: Gen7b
## Type
```
ArgumentOutOfRangeException
```

## Message
```
Arg_ArgumentOutOfRangeException Arg_ParamName_Name, index
```

## Stack trace
```
   at PKHeX.Core.SaveFile.GetBoxSlotFromIndex(Int32 index, Int32& box, Int32& slot)
   at PKHeX.Core.SaveFile.GetBoxSlotOffset(Int32 index)
   at PKHeX.Core.PokeListHeader.GetPartyOffset(Int32 slot)
   at PKHeX.Core.SAV7b.GetPartyOffset(Int32 slot)
   at PKHeX.Core.SaveFile.GetPartySpan(Int32 index)
   at PKHeX.Core.SaveFile.SetPartySlotAtIndex(PKM pk, Int32 index, PKMImportSetting trade, PKMImportSetting dex)
   at PKHeX.Core.SaveFile.set_PartyData(IList`1 value)
   at PKHeX.Facade.PokemonParty.Commit()
   at PKHeX.Facade.Trainer.Commit()
   at PKHeX.Facade.Game.ToByteArray()
   at PKHeX.Web.Services.GameService.Export()
   at PKHeX.Web.Components.LoadGameComponent.ExportSaveAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by arleypadua** [comment]
Can you provide me with some more details of the issue?

I can see from the pre-filled description that you tried to export your save file, but it failed.

But what type of edit did you do before saving?

**Comment by ca122** [comment]
I tried to add a Pokemon to the box. However I tried again with another browser on the same device, iPad, and it worked, so maybe safari has some kind of blocking that may interfere. I would like to report another error with PKHex Web: when I try to load a save file from Pokemon Scarlet it says it’s too large. I have the latest version of the game with all the dlc. 13/08/24 0:18、Arley Pádua ***@***.***>のメール:﻿
Can you provide me with some more details of the issue?
I can see from the pre-filled description that you tried to export your save file, but it failed.
But what type of edit did you do before saving?

**Comment by arleypadua** [comment]
Thanks for the context. 

Regarding the limit on the file size, I just increased it. You should be able to load it now 👍🏽

**Comment by ca122** [comment]
Thank you!! Now it works perfectly!13/08/24 8:37、Arley Pádua ***@***.***>のメール:﻿
Thanks for the context.
Regarding the limit on the file size, I just increased it. You should be able to load it now 👍🏽
