### ISSUE TITLE
Error on PKHeX.Web: Expected 1-6, got 0 Arg_ParamName_Name, value

### ISSUE THREAD

**Issue by bpfreder** [arleypadua/PKHeX.Everywhere#62]
# Error on PKHeX.Web

* **Id**: fe75f12b-829e-48cd-a194-65e0fe796373
* **Game version**: Platinum
* **Generation**: Gen4
## Type
```
ArgumentOutOfRangeException
```

## Message
```
Expected 1-6, got 0 Arg_ParamName_Name, value
```

## Stack trace
```
   at PKHeX.Core.SaveFile.set_PartyData(IList`1 value)
   at PKHeX.Facade.PokemonParty.Commit()
   at PKHeX.Facade.Trainer.Commit()
   at PKHeX.Facade.Game.ToByteArray()
   at PKHeX.Web.Services.GameService.Export()
   at PKHeX.Web.Components.LoadGameComponent.ExportSaveAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by arleypadua** [comment]
I can see that the issue happened when you tried to export the save file, but can you describe a bit the change you've made?

**Comment by arleypadua** [comment]
closed due to no response
