### ISSUE TITLE
Error on PKHeX.Web: None Arg_ParamName_Name, type

### ISSUE THREAD

**Issue by bdawg1989** [arleypadua/PKHeX.Everywhere#71]
# Error on PKHeX.Web

* **Id**: 73dcb656-75d2-4489-aa5f-070d315ab8a6
* **Game version**: Scarlet
* **Generation**: Gen9
## Type
```
ArgumentOutOfRangeException
```

## Message
```
None Arg_ParamName_Name, type
```

## Stack trace
```
   at PKHeX.Core.SCTypeCodeExtensions.GetValue(SCTypeCode type, ReadOnlySpan`1 data)
   at PKHeX.Core.SCBlock.GetValue()
   at PKHeX.Core.SCBlockAccessor.GetBlockValue(UInt32 key)
   at PKHeX.Core.SAV9SV.get_Money()
   at PKHeX.Facade.Money.get_Amount()
   at PKHeX.Web.Pages.Home.<BuildRenderTree>b__0_6(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at AntDesign.Descriptions.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

This happened when I Selected "Scarlet" from the Empty drop down menu on the home screen.

**Comment by arleypadua** [comment]
Thanks for reporting, will look into fixing it.

That usually happens when trying to read the money from an empty file and the parser fails.

Although it fails, you can still navigate to other pages and then click on the button "Dismiss" on the top right corner
