### ISSUE TITLE
Error on PKHeX.Web: ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index

### ISSUE THREAD

**Issue by Tallo39** [arleypadua/PKHeX.Everywhere#72]
# Error on PKHeX.Web

* **Id**: f10bd7dc-689a-491c-a14f-4f389f68ba75
* **Game version**: Violet
* **Generation**: Gen9
## Type
```
ArgumentOutOfRangeException
```

## Message
```
ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index
```

## Stack trace
```
   at PKHeX.Core.FormConverter.GetFormsGen9(UInt16 species, Byte generation, IReadOnlyList`1 types, IReadOnlyList`1 forms, IReadOnlyList`1 genders)
   at PKHeX.Core.FormConverter.GetFormList(UInt16 species, IReadOnlyList`1 types, IReadOnlyList`1 forms, IReadOnlyList`1 genders, EntityContext context)
   at PKHeX.Facade.Repositories.FormRepository.GetFor(Species species, EntityContext context)
   at PKHeX.Facade.Repositories.FormRepository.GetFor(PKM pokemon)
   at PKHeX.Facade.Pokemons.PokemonForm.get_Form()
   at PKHeX.Web.Components.PokemonTable.<>c__DisplayClass0_0.<BuildRenderTree>b__4(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at AntDesign.Column`1[[PKHeX.Facade.Repositories.SpeciesDefinition, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__170_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at Microsoft.AspNetCore.Components.CascadingValue`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

**Comment by ahsatan** [comment]
I had the same issue while loading a save from emulating Scarlet with the Compass mod.  Not sure which Pokemon is causing the issue.

**Comment by arleypadua** [comment]
just pushed a new version that should be out in 1 or 2 minutes that should fix it 👍🏽 

thanks for letting me know
