### ISSUE TITLE
Error on PKHeX.Web: Expected 1-6, got 0 Arg_ParamName_Name, value

### ISSUE THREAD

**Issue by genpansam** [arleypadua/PKHeX.Everywhere#81]
# Error on PKHeX.Web

* **Id**: da04bc5b-c1f9-41a7-b0fd-ec84be5e3955
* **Game version**: Shining Pearl
* **Generation**: Gen8b
## Type
```
ArgumentOutOfRangeException
```

## Message
```
Expected 1-6, got 0 Arg_ParamName_Name, value
```

## Stack trace
```
   at PKHeX.Core.SaveFile.set_PartyData(IList`1 value)
   at PKHeX.Facade.PokemonParty.Commit()
   at PKHeX.Facade.Trainer.Commit()
   at PKHeX.Facade.Game.ToByteArray()
   at PKHeX.Web.Services.GameService.Export()
   at PKHeX.Web.Components.LoadGameComponent.ExportSaveAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by arleypadua** [comment]
can't to reproduce the issue
