### ISSUE TITLE
Error on PKHeX.Web: ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index

### ISSUE THREAD

**Issue by ahsatan** [arleypadua/PKHeX.Everywhere#97]
I've been using PXHeX with Pokemon Scarlet on an emulator with the Compass mod.  Accessing the Pokemon Box used to work but now gives the following error.  The error seems to regard a Pokemon form and since Compass makes changes to some Pokemon I'm guessing it's related to that but I can't tell which Pokemon/what change that might be.

# Error on PKHeX.Web

* **Id**: 560bd608-f92b-435a-9ca3-ce6798cd29f5
* **Game version**: Scarlet
* **Generation**: Gen9
## Type
```
ArgumentOutOfRangeException
```

## Message
```
ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index
```

## Stack trace
```
   at PKHeX.Core.FormConverter.GetFormsGen9(UInt16 species, Byte generation, IReadOnlyList`1 types, IReadOnlyList`1 forms, IReadOnlyList`1 genders)
   at PKHeX.Core.FormConverter.GetFormList(UInt16 species, IReadOnlyList`1 types, IReadOnlyList`1 forms, IReadOnlyList`1 genders, EntityContext context)
   at PKHeX.Facade.Repositories.FormRepository.GetFor(Species species, EntityContext context)
   at PKHeX.Facade.Repositories.FormRepository.GetFor(PKM pokemon)
   at PKHeX.Facade.Pokemons.PokemonForm.get_Form()
   at PKHeX.Web.Components.PokemonTable.<>c__DisplayClass0_0.<BuildRenderTree>b__4(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at AntDesign.Column`1[[PKHeX.Facade.Repositories.SpeciesDefinition, PKHeX.Facade, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__170_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at Microsoft.AspNetCore.Components.CascadingValue`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

**Comment by ahsatan** [comment]
Ah, just noticed it looks like a duplicate of an already reported issue - I'll try to mark it as such.  Let me know if I can provide any further information.
